# Generated by Django 4.0.3 on 2022-03-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='professor',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='rmp.professor'),
            preserve_default=False,
        ),
    ]
