# Generated by Django 4.0.3 on 2022-03-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmp', '0004_module_professor_rating_module_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='professor',
        ),
    ]
